# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', path: '../node_modules/react-native'
  pod 'react-native-geo-fencing', path: '../node_modules/react-native-geo-fencing'
end
  # Pods for testing

  target 'testing-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testingTests' do
    inherit! :search_paths
    # Pods for testing
  end

target 'testing-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testing-tvOS

  

end
